import React from "react";
import { graphql, Link } from "gatsby";
import { getImage } from "gatsby-plugin-image";

import Seo from "../components/seo";
import NewsletterForm from "../components/newsletter";
import MainMenu from "../content/main-menu";
import SocialLinks from "../content/social-links";

const QueenEmail = ({ data, ...props }) => {
  const {
    frontmatter: { title, description },
    html,
    excerpt,
    ogImage,
    parent: { date },
  } = data.markdownRemark;

  const ogGatsbyImage = getImage(ogImage);

  const body = `<p>Hello there, </p>` + html;

  return (
    <>
      <Seo
        {...props}
        meta={{
          title: title,
          description: description || excerpt,
          image: ogGatsbyImage?.images?.fallback?.src,
          alt: `Autogenerated social image for "${title}"`,
        }}
      />
      <main>
        <header>
          <h1>{title}</h1>
          <small>
            An <Link to="/emails">email</Link> sent by{" "}
            <Link to="/">Queen Raae</Link>&nbsp;👑 on {date}
          </small>
        </header>

        <div dangerouslySetInnerHTML={{ __html: body }} />

        <section>
          <NewsletterForm formKey="queen">
            <p>
              I send emails like this one to{" "}
              <strong>help you get the most out of Gatsby</strong> multiple
              times a week. Sign up to get them delivered to your inbox.
            </p>
          </NewsletterForm>
        </section>
      </main>

      <footer>
        <nav>
          <MainMenu />
          <SocialLinks />
        </nav>
      </footer>
    </>
  );
};

export default QueenEmail;

export const query = graphql`
  query MarkdownByQueenEmailId($id: String!) {
    markdownRemark(parent: { id: { eq: $id } }) {
      parent {
        ... on QueenEmail {
          date(formatString: "MMMM Do, YYYY")
        }
      }
      excerpt(pruneLength: 160)
      html
      frontmatter {
        title
        description
      }
      ogImage {
        childImageSharp {
          gatsbyImageData
        }
      }
    }
  }
`;
